In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/Jcharis/Python-Machine-Learning/master/Gender%20Classification%20With%20%20Machine%20Learning/names_dataset.csv')

In [4]:
df.head()

index       name sex
0      0       Mary   F
1      1       Anna   F
2      2       Emma   F
3      3  Elizabeth   F
4      4     Minnie   F

In [5]:
df.size


285075

In [6]:
df_names=df

In [7]:
df_names.sex.replace({"F":0,"M":1},inplace=True)

In [8]:
df_names.head()

index       name  sex
0      0       Mary    0
1      1       Anna    0
2      2       Emma    0
3      3  Elizabeth    0
4      4     Minnie    0

In [9]:
Xfeatures=df_names['name']# Feature Extraction 
cv = CountVectorizer()
X = cv.fit_transform(Xfeatures)

In [10]:
cv.get_feature_names()

['aaban',
 'aabha',
 'aabid',
 'aabriella',
 'aada',
 'aadam',
 'aadan',
 'aadarsh',
 'aaden',
 'aadesh',
 'aadhav',
 'aadhavan',
 'aadhi',
 'aadhira',
 'aadhvik',
 'aadhya',
 'aadhyan',
 'aadi',
 'aadian',
 'aadil',
 'aadin',
 'aadish',
 'aadison',
 'aadit',
 'aadith',
 'aadithya',
 'aaditri',
 'aaditya',
 'aadiv',
 'aadon',
 'aadrian',
 'aadrika',
 'aadrit',
 'aadvik',
 'aadvika',
 'aadya',
 'aadyn',
 'aafia',
 'aafreen',
 'aagam',
 'aage',
 'aagot',
 'aahaan',
 'aahan',
 'aahana',
 'aahil',
 'aahir',
 'aahliyah',
 'aahna',
 'aahron',
 'aaidan',
 'aaiden',
 'aaidyn',
 'aaila',
 'aailiyah',
 'aailyah',
 'aaima',
 'aaira',
 'aairah',
 'aaisha',
 'aaishah',
 'aaiyana',
 'aaiza',
 'aaja',
 'aajah',
 'aajaylah',
 'aajon',
 'aakanksha',
 'aakarsh',
 'aakash',
 'aakeem',
 'aakilah',
 'aakira',
 'aakiyah',
 'aakriti',
 'aala',
 'aalaiya',
 'aalaiyah',
 'aalana',
 'aalanah',
 'aalani',
 'aalap',
 'aalaya',
 'aalayah',
 'aalayiah',
 'aalayjah',
 'aalayna',
 'aalaysha',
 'aalaysia',
 'aalea',
 

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
# Labels
y = df_names.sex

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

Naive bayes 

In [14]:
from sklearn.naive_bayes import MultinomialNB

In [15]:
clf=MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6398163206734908

In [16]:
print("accuracy = ",clf.score(X_test,y_test),"%")

accuracy =  0.6398163206734908 %


In [17]:
sample_name=["Marco"]
vect=cv.transform(sample_name).toarray()
vect

array([[0, 0, 0, ..., 0, 0, 0]])

## Here "1" is male and "0" is female

In [18]:
clf.predict(vect)

array([1])

In [19]:
#another prediction 
sample_name2=["Suman"]
vect=cv.transform(sample_name2).toarray()
clf.predict(vect)

array([0])

In [20]:
#prediction of array of random names
names=["Raj","Raman","Anshu","Sumit"]
vect3=cv.transform(names).toarray()
clf.predict(vect3)

array([1, 1, 0, 0])

In [21]:
def genderpredictor(a):
    test_name=[a]
    vector=cv.transform(test_name).toarray()
    if clf.predict(vector)==0:
        print("female")
    else:
        print("male")

In [22]:
genderpredictor("Mark")

male


### Using a custom function for feature analysis

In [23]:
# By Analogy most female names ends in 'A' or 'E' or has the sound of 'A'
def features(name):
    name = name.lower()
    return {
        'first-letter': name[0], # First letter
        'first2-letters': name[0:2], # First 2 letters
        'first3-letters': name[0:3], # First 3 letters
        'last-letter': name[-1],
        'last2-letters': name[-2:],
        'last3-letters': name[-3:],
    }

In [24]:
# Vectorize the features function
features = np.vectorize(features)
print(features(["Anna", "Peter","John","Mohammed"]))

[{'first-letter': 'a', 'first2-letters': 'an', 'first3-letters': 'ann', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'nna'}
 {'first-letter': 'p', 'first2-letters': 'pe', 'first3-letters': 'pet', 'last-letter': 'r', 'last2-letters': 'er', 'last3-letters': 'ter'}
 {'first-letter': 'j', 'first2-letters': 'jo', 'first3-letters': 'joh', 'last-letter': 'n', 'last2-letters': 'hn', 'last3-letters': 'ohn'}
 {'first-letter': 'm', 'first2-letters': 'mo', 'first3-letters': 'moh', 'last-letter': 'd', 'last2-letters': 'ed', 'last3-letters': 'med'}]


In [25]:
# Extract the features for the dataset
df_X = features(df_names['name'])

In [26]:
df_y=df_names['sex']

In [27]:
from sklearn.feature_extraction import DictVectorizer
 
corpus = features(["Sid", "Akash"])
dv = DictVectorizer()
dv.fit(corpus)
transformed = dv.transform(corpus)
print(transformed)

  (0, 1)	1.0
  (0, 3)	1.0
  (0, 5)	1.0
  (0, 6)	1.0
  (0, 8)	1.0
  (0, 11)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (1, 4)	1.0
  (1, 7)	1.0
  (1, 9)	1.0
  (1, 10)	1.0


In [28]:
dv.get_feature_names()

['first-letter=a',
 'first-letter=s',
 'first2-letters=ak',
 'first2-letters=si',
 'first3-letters=aka',
 'first3-letters=sid',
 'last-letter=d',
 'last-letter=h',
 'last2-letters=id',
 'last2-letters=sh',
 'last3-letters=ash',
 'last3-letters=sid']

In [29]:
dfX_train, dfX_test, dfy_train, dfy_test = train_test_split(df_X, df_y, test_size=0.33, random_state=42)

In [30]:
dv = DictVectorizer()
dv.fit_transform(dfX_train)

<63666x8194 sparse matrix of type '<class 'numpy.float64'>'
	with 381996 stored elements in Compressed Sparse Row format>

In [31]:
#decision tree
from sklearn.tree import DecisionTreeClassifier
 
dclf = DecisionTreeClassifier()
my_xfeatures =dv.transform(dfX_train)
dclf.fit(my_xfeatures, dfy_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [32]:
# Build Features and Transform them
sample_name_eg = ["Sumit"]
transform_dv =dv.transform(features(sample_name_eg))

In [33]:
vect3 = transform_dv.toarray()

In [34]:
dclf.predict(vect3)

array([1])

In [35]:
if dclf.predict(vect3) == 0:
    print("Female")
else:
    print("Male")

Male


In [36]:
# Second Prediction With Russian names
name_eg1 = ["Reznov"]
transform_dv =dv.transform(features(name_eg1))
vect4 = transform_dv.toarray()
if dclf.predict(vect4) == 0:
    print("Female")
else:
    print("Male")

Male


In [37]:
def genderpredictor1(a):
    test_name1 = [a]
    transform_dv =dv.transform(features(test_name1))
    vector = transform_dv.toarray()
    if dclf.predict(vector) == 0:
        print("Female")
    else:
        print("Male")

In [38]:
random_name_list = ["Alex","Alice","Chioma","Niko","Chang"]

In [39]:
for n in random_name_list:
    print(genderpredictor1(n))

Male
None
Female
None
Female
None
Female
None
Male
None


In [40]:
# Accuracy on training set
print(dclf.score(dv.transform(dfX_train), dfy_train))

0.9888951716771903


In [41]:
# Accuracy on test set
print(dclf.score(dv.transform(dfX_test), dfy_test))

0.8660671577537549


In [42]:
genderpredictor1('Anmol')

Male


In [43]:
genderpredictor1('Siddhant')

Male


In [44]:
genderpredictor1('Suman')

Female


In [45]:
genderpredictor('Rashmi')

female


In [48]:
from sklearn.model_selection import KFold

In [50]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics

In [60]:
scores = cross_val_score(dclf,my_xfeatures, dfy_train, cv=15)


In [61]:
scores

array([0.85865724, 0.86360424, 0.86195524, 0.86007067, 0.85795053,
       0.85889282, 0.86475024, 0.8706409 , 0.87393968, 0.86639962,
       0.866164  , 0.86239397, 0.86663525, 0.86781338, 0.85485391])